# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 15:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=1000)),
                ('amobile_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('apassword', models.CharField(default='', max_length=1000)),
                ('adesignation', models.CharField(default='', max_length=50)),
                ('aemail', models.EmailField(max_length=1000)),
                ('atype', models.CharField(default='Proctore', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('complain_txt', models.CharField(max_length=1000)),
                ('attachment', models.CharField(default='no', max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='not processed', max_length=100)),
                ('share_status', models.CharField(default='no', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complain_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting', models.CharField(default='yes', max_length=100)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Authority')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Complain')),
            ],
        ),
        migrations.CreateModel(
            name='Notification_Authority',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('notifcation', models.CharField(default='', max_length=5000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('type_n', models.CharField(default='proctore', max_length=100)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Authority')),
            ],
        ),
        migrations.CreateModel(
            name='Notification_Students',
            fields=[
                ('nsid', models.AutoField(primary_key=True, serialize=False)),
                ('notifcation', models.CharField(default='', max_length=5000)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('mobile_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('g_mobile_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='student_details',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Students'),
        ),
        migrations.AddField(
            model_name='notification_students',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Students'),
        ),
        migrations.AddField(
            model_name='complain',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Students'),
        ),
    ]
