# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='atype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
