# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20171109_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='abranch',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='authority',
            name='adesignation',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
